### ISSUE TITLE
issue with conda 3.18.3

### ISSUE THREAD

**Issue by licode** [NSLS-II-HXN/PyXRF#58]
Use latest conda version 3.18, and run ```conda install -c licode pyxrf```, get errors. However, things work fine for conda 3.9.

Traceback (most recent call last):
  File "/home/lili/mc/envs/pyxrf_nov15/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/lili/mc/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/lili/mc/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/lili/mc/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/lili/mc/lib/python2.7/site-packages/conda/cli/install.py", line 333, in install
    update_deps=args.update_deps)
  File "/home/lili/mc/lib/python2.7/site-packages/conda/plan.py", line 406, in install_actions
    add_defaults_to_specs(r, linked, specs)
  File "/home/lili/mc/lib/python2.7/site-packages/conda/plan.py", line 350, in add_defaults_to_specs
    for spec in specs
  File "/home/lili/mc/lib/python2.7/site-packages/conda/plan.py", line 351, in <genexpr>
    for fn in r.get_max_dists(MatchSpec(spec))
  File "/home/lili/mc/lib/python2.7/site-packages/conda/resolve.py", line 563, in get_max_dists
    pkgs = self.get_pkgs(ms, max_only=True)
  File "/home/lili/mc/lib/python2.7/site-packages/conda/resolve.py", line 544, in get_pkgs
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/home/lili/mc/lib/python2.7/site-packages/conda/resolve.py", line 360, in __init__
    self.norm_version = VersionOrder(self.version)
  File "/home/lili/mc/lib/python2.7/site-packages/conda/resolve.py", line 187, in __init__
    raise ValueError(message + "empty version component.")
ValueError: Malformed version string '.post': empty version component.

Conda info as below:

(pyxrf_nov15)lili@xf03idc-ws2:~/git_code/PyXRF$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.3
  conda-build version : 1.14.0
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /home/lili/mc  (writable)
  default environment : /home/lili/mc/envs/pyxrf_nov15
     envs directories : /home/lili/mc/envs
        package cache : /home/lili/mc/pkgs
         channel URLs : https://conda.nsls2.bnl.gov/conda/latest/linux-64/
                        https://conda.nsls2.bnl.gov/conda/latest/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/anaconda/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/anaconda/noarch/
          config file : /home/lili/.condarc
    is foreign system : False

**Comment by licode** [comment]
fixed. Pay attention to -v.0.3.post10- part in the name of package pyxrf-v0.0.3.post10-10_g187e184_py27.tar.bz2.
